name = "duongtrang/my-gift-contract"
version = "0.0.0"
compiler = "v1.1.21"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'duongtrang/my-gift-contract'"

[repository]
user = "duongtrang"
project = "my-gift-contract"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v3.0.0"
source = "github"

[config]
